### ISSUE TITLE
Suggestion: turn plugin on/off for current windows using Ctrl Shift P

### ISSUE THREAD

**Issue by ttpro1995** [braver/typewriter#20]
Sometimes, the file I am writing is not markdown (well, not even have extension). An I need a quickly way to turn on plugin for that file.

**Comment by iCodeForBananas** [comment]
@braver Do you know of a code example for keyboard shortcuts?

**Comment by braver** [comment]
I *think* it simply looks for a `.cson` file in a keymaps dir, and `<package>:toggle` maps to enabling/disabling a package. I.e. turning on/off packages through keybindings isn't something a package needs to support, Atom should already support this. It's not necessarily recommended for packages to have keybindings baked in because they tend to clash with between packages, so the recommended thing to do here is figure out which command to call and perhaps put that in the readme.

**Comment by iCodeForBananas** [comment]
At some point I'll figure this out because I'd like to use it too.

**Comment by iCodeForBananas** [comment]
@ttpro1995 If you're in a pinch I recommend checking out https://atom.io/packages/toggle-packages.  I'm going to leave this as is for now unless someone makes a pull request.
