### ISSUE TITLE
soft wrap appears off by one?

### ISSUE THREAD

**Issue by cyphunk** [braver/typewriter#29]
Thank you for this great tool. Please ignore this and close it if I've clearly misunderstood somthing

![screenshot from 2018-11-24 01-07-51](https://user-images.githubusercontent.com/119662/48962848-9ccae980-ef86-11e8-8151-783a9fba29f0.png)

The text shown was hard wrapped with the ctrl+shift+q so that the text is formatted hard to 80 char width
80 char is the width set in the editor main settings that I think typewriter also depends on.

one thing to notice is that the scroll bar is enabled. I've set in typewriter this sitting off which should mean the scroll bar is not on, but it still is. However, that may be a different issue

if this is an issue you've seen before just let me know and ill go rtfm. if not, feel free to close. atom.io is a swamp and I'm guessing the issue could be in a different plugin

thanks

**Comment by WispOfTheWinds** [comment]
I just ran into the same issue. I forked the project and I'm starting to look into it.

**Comment by uliska** [comment]
I too find this very much annoying, and I see the same as in the original Issue description's screenshot.

For now a workaround is to use the `Draw Text Left Aligned` option (simply because that leaves more space, at least on my screen), but I would really like to also use the centered layout, which is currently not possible for all those who want to use hard line breaks.

@braver don't you have the chance to look into the open Pull Request by @WispOfTheWinds  ?

**Comment by braver** [comment]
I published 0.8.0 just now with #30 merged. Hope that works out for everyone.

PS. If anyone wants access to this repo to maintain it and publish fixes, let me know.
